const prodObj = [
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9241.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-100%",
      "title": "Tupperware Bowled Over Plastic Container Set, 450Ml, Set Of 2, Multicolour, Blue",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9392,490.00",
      "canAddToCart": false,
      "totalReviewCount": 1018,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 3.9,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/514PZ1VzBEL.jpg",
      "asin": "B00HXQOY92",
      "productLink": "/dp/B00HXQOY92/ref=va_live_carousel",
      "brand": "Tupperware",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9129.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-68%",
      "title": "Lifeplast Unbreakable Welcome Small Serving Snacks Platter/Tray/Plastic (Pack of 1) (Black)",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9399.00",
      "canAddToCart": false,
      "totalReviewCount": 20,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/21AvmPupjCL.jpg",
      "asin": "B098KWFFB4",
      "productLink": "/dp/B098KWFFB4/ref=va_live_carousel",
      "brand": "Lifeplast",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9400.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-20%",
      "title": "Tupperware Modular Mates Oval #2 Storage Box, 1.1 litres (102)",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9500.00",
      "canAddToCart": false,
      "totalReviewCount": 103,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.2,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/4195cPsKqYL.jpg",
      "asin": "B00GQUU4VS",
      "productLink": "/dp/B00GQUU4VS/ref=va_live_carousel",
      "brand": "Tupperware",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9782.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-22%",
      "title": "La Opala Diva, Cosmo Collection, Opal Glass Soup Bowl Set 6 Pcs, Plainware, White, 0.33 Liters",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9999.00",
      "canAddToCart": false,
      "totalReviewCount": 57,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/31B+FXvdKDL.jpg",
      "asin": "B08XVXVS4T",
      "productLink": "/dp/B08XVXVS4T/ref=va_live_carousel",
      "brand": "La Opala",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9999.00",
      "hasHalfStar": true,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-35%",
      "title": "Borosil Glass Serving & Mixing Bowls With Lids, Oven & Microwave Safe Bowls, Set of 3 (500 ml + 900 ml + 1.3 L), Borosilicate Glass, Clear",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b91,545.00",
      "canAddToCart": false,
      "totalReviewCount": 9181,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.4,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41z959WlUTL.jpg",
      "asin": "B07BHB1FJS",
      "productLink": "/dp/B07BHB1FJS/ref=va_live_carousel",
      "brand": "Borosil",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9744.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-26%",
      "title": "The Earth Store Handcrafted Ceramic Multicolor Tribal Art Microwave Safe Chai/Tea Glasses/Serving Tea Kullad Cups Set Best Gift for Friends, Anniversary, Birthday",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9999.00",
      "canAddToCart": false,
      "totalReviewCount": 261,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/51BSp9ByppL.jpg",
      "asin": "B08Z7RSWVX",
      "productLink": "/dp/B08Z7RSWVX/ref=va_live_carousel",
      "brand": "The Earth Store",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "26% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9299.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-13%",
      "title": "Borosil - Glass Vision Classic Delite 305 Ml (Set of 2) - Tea and Coffee Mug, Transparent",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9345.00",
      "canAddToCart": false,
      "totalReviewCount": 1143,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.2,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/31kvRk5JEZL.jpg",
      "asin": "B01M9JNOAX",
      "productLink": "/dp/B01M9JNOAX/ref=va_live_carousel",
      "brand": "Borosil",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "13% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9227.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-62%",
      "title": "ATOM Digital Kitchen Weighing Scale & Food Weight Machine for Health, 10kg X 1gm, Fitness, Home Baking & Cooking, White. For Domestic Use Only (SF400) | 2 Batteries included",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9599.00",
      "canAddToCart": false,
      "totalReviewCount": 2171,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 3.9,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/310C8cNuyyL.jpg",
      "asin": "B083C6XMKQ",
      "productLink": "/dp/B083C6XMKQ/ref=va_live_carousel",
      "brand": "Aliston",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "62% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9829.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-67%",
      "title": "Amazon Brand - Solimo Air-Tight Dry Fruit Container Tray Set With Lid & Serving Tray, Airtight Plastic Storage Container Set 500 ml | Set of 4, Black",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b92,499.00",
      "canAddToCart": false,
      "totalReviewCount": 108,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/51d6jvK5imL.jpg",
      "asin": "B0BYNYY3LL",
      "productLink": "/dp/B0BYNYY3LL/ref=va_live_carousel",
      "brand": "Amazon Brand - Solimo",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "67% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9654.00",
      "hasHalfStar": true,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-35%",
      "title": "DULI Set of 2 MDF Wood Trays Enamel Coated| Round Wooden Serving Trays | Kitchen&Dining Decorative | Resin Tray | Handmade | 7x7 & 9x9 inches (Setof2Round: AquaGoldBirds)",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9999.00",
      "canAddToCart": false,
      "totalReviewCount": 218,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.3,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/412hVVpJyuL.jpg",
      "asin": "B0BH8RXC38",
      "productLink": "/dp/B0BH8RXC38/ref=va_live_carousel",
      "brand": "DULI",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "35% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9635.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-47%",
      "title": "Ganesh 14 in 1 Multipurpose Chopper, Fruits & Vegetable Cutters, Grater Peeler Chipser, Unbreakable Food Grade Body, Easy Push to Clean Button Slicer Dicer, Chopper for Kitchen (Green, Plastic)",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b91,190.00",
      "canAddToCart": false,
      "totalReviewCount": 45360,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41v25mRBOsL.jpg",
      "asin": "B01BVDS1BE",
      "productLink": "/dp/B01BVDS1BE/ref=va_live_carousel",
      "brand": "GANESH",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "47% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b999.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-50%",
      "title": "Clazkit Plastic Dry Fruit/Masala Box 4 Sections Multipurpose Box- Color May Vary",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9199.00",
      "canAddToCart": false,
      "totalReviewCount": 259,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/31hGiK8GYIL.jpg",
      "asin": "B0BX6XGSTG",
      "productLink": "/dp/B0BX6XGSTG/ref=va_live_carousel",
      "brand": "Clazkit",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9899.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-55%",
      "title": "KONVIO Melamine Dinner Full Size Plates Set of 6, Unbreakable Plates (6 Pieces, 11 inches) (Rich - Black)",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b91,999.00",
      "canAddToCart": false,
      "totalReviewCount": 162,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41vstMzxwGL.jpg",
      "asin": "B09QKY15LB",
      "productLink": "/dp/B09QKY15LB/ref=va_live_carousel",
      "brand": "KONVIO",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9957.00",
      "hasHalfStar": true,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-40%",
      "title": "Milton Euroline Combo Set Go Electro Stainless Steel Electric Kettle, Silver, 1.2 Litre, 1 Piece and Alive Stainless Steel Water Bottle, Black, 750 ml, 1 Piece",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b91,594.00",
      "canAddToCart": false,
      "totalReviewCount": 73,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.3,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41E73I2ZzuS.jpg",
      "asin": "B092SW67PV",
      "productLink": "/dp/B092SW67PV/ref=va_live_carousel",
      "brand": "MILTON",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9759.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-44%",
      "title": "MARKET 99 Tea & Sugar Jar Set Of 2 For Home & Kitchen Storage Box Dabba Container 900 Ml, GALVANISED IRON",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b91,349.00",
      "canAddToCart": false,
      "totalReviewCount": 187,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41farGM1pBL.jpg",
      "asin": "B0BMLSNDH3",
      "productLink": "/dp/B0BMLSNDH3/ref=va_live_carousel",
      "brand": "MARKET 99",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "44% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9298.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-57%",
      "title": "12FOR COLLECTION 2pcs Stainless Steel Kitchen Dish Rack Expandable Storage Shelves for Kitchen Cabinets Multipurpose Organizer Extend Up to 580 mm with Anti-Rust Nano Coating (Pack of 2)",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9699.00",
      "canAddToCart": false,
      "totalReviewCount": 1710,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/31nwpuMCtQL.jpg",
      "asin": "B09XDQZHW2",
      "productLink": "/dp/B09XDQZHW2/ref=va_live_carousel",
      "brand": "12FOR COLLECTION",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9829.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-67%",
      "title": "Amazon Brand - Solimo Air-Tight Dry Fruit Container Tray Set With Lid & Serving Tray, Airtight Plastic Storage Container Set 500 ml | Set of 4, White",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b92,499.00",
      "canAddToCart": false,
      "totalReviewCount": 108,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/413tucu6m4L.jpg",
      "asin": "B0BYNW71KD",
      "productLink": "/dp/B0BYNW71KD/ref=va_live_carousel",
      "brand": "Amazon Brand - Solimo",
      "dealBadge": {
          "messageText": "Ends in ",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": "2024-03-19T18:15Z",
          "labelBackgroundColor": "CC0C39",
          "labelText": "67% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9999.00",
      "hasHalfStar": true,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-67%",
      "title": "MILTON Ernesto Inner Stainless Steel Jr. Casserole Set of 3 (420 ml, 850 ml, 1.43 litres), Grey | Easy to Carry | Serving | Stackable",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b92,999.00",
      "canAddToCart": false,
      "totalReviewCount": 4368,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 3,
      "digitalProduct": false,
      "ratingValue": 3.7,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41Lj5tdmdOL.jpg",
      "asin": "B0B6RH5JRL",
      "productLink": "/dp/B0B6RH5JRL/ref=va_live_carousel",
      "brand": "MILTON",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9743.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-58%",
      "title": "Anwaliya Edesia Series Coffee Mug - Ceramic Set of 6 (280ml) Handcrafted Design Tea Cups Set of 6 Stackable, Chip Resistant, with Handles Large Serving Coffee Cup, Naomi (Black)",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b91,766.00",
      "canAddToCart": false,
      "totalReviewCount": 4049,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.2,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41QUxWrqryL.jpg",
      "asin": "B08HWKRKLY",
      "productLink": "/dp/B08HWKRKLY/ref=va_live_carousel",
      "brand": "Anwaliya",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "58% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9299.00",
      "hasHalfStar": true,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-70%",
      "title": "e kysa dailly Melamine Platter/Tray for Serving Snacks - Black Color, Rectangular Shape (32 * 13 cm)",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b91,000.00",
      "canAddToCart": false,
      "totalReviewCount": 3,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.4,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/311z0LbJQCL.jpg",
      "asin": "B0CGRP6TTF",
      "productLink": "/dp/B0CGRP6TTF/ref=va_live_carousel",
      "brand": "e kysa dailly",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9239.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-76%",
      "title": "Artvibes Wooden Wall Hanger for Home | Office | Living Room | Gift | Modern Decoration Items | Kitchen Wall Decor |Rajasthani Culture Home Decor Hanging Items (WH_5012N), Set of 3",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9999.00",
      "canAddToCart": false,
      "totalReviewCount": 1558,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.2,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41rQbmzLYuL.jpg",
      "asin": "B09YRZ734R",
      "productLink": "/dp/B09YRZ734R/ref=va_live_carousel",
      "brand": "Artvibes",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "76% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9199.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-43%",
      "title": "Ikea Plastic Plate - Pack of 6, Multicolour",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9349.00",
      "canAddToCart": false,
      "totalReviewCount": 270,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.2,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/21xIYmQ0mtL.jpg",
      "asin": "B07X4877RR",
      "productLink": "/dp/B07X4877RR/ref=va_live_carousel",
      "brand": "Ikea",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9775.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-40%",
      "title": "Axmon Metal Pan And Pot Rack Organizer For Kitchen - 5 Tier Adjustable Compartments Kitchen Utensil, Tawa Rack Holder Stand Plate Dish Lid Tray Cookware Cabinet Storage Shelf, WIRE,Freestanding",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b91,299.00",
      "canAddToCart": false,
      "totalReviewCount": 1211,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 3.9,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41DElQzBpyL.jpg",
      "asin": "B08BPJH62K",
      "productLink": "/dp/B08BPJH62K/ref=va_live_carousel",
      "brand": "Axmon",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9240.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-47%",
      "title": "Clazkit Stainless Steel Chopping Board Vegetable,Fruit Cutter(Size 31.8CM X 21CM)",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9449.00",
      "canAddToCart": false,
      "totalReviewCount": 573,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/31h69AeTqSL.jpg",
      "asin": "B0CG6G6HCB",
      "productLink": "/dp/B0CG6G6HCB/ref=va_live_carousel",
      "brand": "Clazkit",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "47% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9699.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-30%",
      "title": "MosQuick® Egg tray box 30 eggs Egg Box Eggs Storage Box, Egg Container for Fridge, Egg Holder - Ideal Egg storage box for fridge Egg tray for fridge - Durable Egg Tray, Egg Crate, Egg holder",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b91,000.00",
      "canAddToCart": false,
      "totalReviewCount": 53,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41CTuzpi4LL.jpg",
      "asin": "B0C1JFTJ7W",
      "productLink": "/dp/B0C1JFTJ7W/ref=va_live_carousel",
      "brand": "MosQuick",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "30% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9170.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": null,
      "title": "Signoraware Slim Compartment Lunch Box, Bpa Free Plastic, Microwave Safe Food Grade Tiffin Boxes for Office School, Leak Proof Air Tight Compact Dabba (610ml, Square, Pink, 2 Section Storage)",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": null,
      "canAddToCart": false,
      "totalReviewCount": 2155,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41RApQpgFAL.jpg",
      "asin": "B00JJH91IM",
      "productLink": "/dp/B00JJH91IM/ref=va_live_carousel",
      "brand": "Signoraware",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9695.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": null,
      "title": "Borosil - Carafe Flame Proof Glass Kettle with Stainer, 1.2L",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": null,
      "canAddToCart": false,
      "totalReviewCount": 562,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41OCV8ZxI7L.jpg",
      "asin": "B00E97M8GY",
      "productLink": "/dp/B00E97M8GY/ref=va_live_carousel",
      "brand": "Borosil",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9150.00",
      "hasHalfStar": true,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-83%",
      "title": "Ikea Plastic Polypropylene Mug - 6 Pieces, Multicolour, 230 ML",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9899.00",
      "canAddToCart": false,
      "totalReviewCount": 397,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.3,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41oDbKMhl4L.jpg",
      "asin": "B07PXYQ1Y5",
      "productLink": "/dp/B07PXYQ1Y5/ref=va_live_carousel",
      "brand": "Ikea",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9219.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-56%",
      "title": "Wolpin 1 Pc Spoon Holder Spatula Holder for Kitchen Spoon Rest Cooking Utensil Plastic Stand Pan Cover Lid Rack Pot Clips Support Ladle Organizer Tool (17 x 15 x 8 cm)",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9499.00",
      "canAddToCart": false,
      "totalReviewCount": 192,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41jkbWo8VQL.jpg",
      "asin": "B0B91CYHS4",
      "productLink": "/dp/B0B91CYHS4/ref=va_live_carousel",
      "brand": "wolpin",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "56% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9495.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-34%",
      "title": "HOKIPO PVC Washable Mats for Dining Table - 45x30 cm Placemats, Set of 4, AR890, Polyvinyl Chloride",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9749.00",
      "canAddToCart": false,
      "totalReviewCount": 995,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41QRI43jW-L.jpg",
      "asin": "B01LZ2ECGJ",
      "productLink": "/dp/B01LZ2ECGJ/ref=va_live_carousel",
      "brand": "HOKIPO",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "34% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9750.00",
      "hasHalfStar": true,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-50%",
      "title": "Nestasia Microwave & Dishwasher Safe Ceramic Bowl Set of 4 | Ideal for Snacks, Rice, Dal, Fruits, Salad, and More | BPA & Lead-Free Dinner Bowls | 350ml, White & Blue",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b91,500.00",
      "canAddToCart": false,
      "totalReviewCount": 704,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.6,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/31MnWNG+oWL.jpg",
      "asin": "B0B97J9Y2G",
      "productLink": "/dp/B0B97J9Y2G/ref=va_live_carousel",
      "brand": "Nestasia",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "50% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9329.00",
      "hasHalfStar": true,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-40%",
      "title": "Floraware Unbreakable Kitchen Sink Dish Driying Corner, Dish Drainer and Drying Rack for Kitchen, Space Saving (White)",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9550.00",
      "canAddToCart": false,
      "totalReviewCount": 159,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 3,
      "digitalProduct": false,
      "ratingValue": 3.7,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41kBzRTokWL.jpg",
      "asin": "B0C5JV475L",
      "productLink": "/dp/B0C5JV475L/ref=va_live_carousel",
      "brand": "Floraware",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "40% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9499.00",
      "hasHalfStar": true,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-50%",
      "title": "AZTEC Cookie Jar 2 Large Glass Jar With Glass Lid Cookie Jars for Kitchen Counter with Lids, Candy Jar, Decorative Apothecary Jar, Large Canisters, Half Gallon 650ml Glass Jar with Lid Airtight",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9999.00",
      "canAddToCart": false,
      "totalReviewCount": 19,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.3,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/511I15ggo1S.jpg",
      "asin": "B0BD8L6Q48",
      "productLink": "/dp/B0BD8L6Q48/ref=va_live_carousel",
      "brand": "AZTEC",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9399.00",
      "hasHalfStar": true,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-60%",
      "title": "MARKETING PORIUM Cutlery Holder | Rustic Spoon Stand for Kitchen | Kitchen Decor Item | Metal Spoon Holder | Spoon Stand for Dining Table Kitchen Accessories (Off-White)",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9999.00",
      "canAddToCart": false,
      "totalReviewCount": 24,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.4,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41l4CYGq4BL.jpg",
      "asin": "B0CHGZZFSK",
      "productLink": "/dp/B0CHGZZFSK/ref=va_live_carousel",
      "brand": "MARKETING PORIUM",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": null,
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": null,
      "title": "YouBee Air-Tight Dry Fruit Container Tray Set with Lid & Serving Tray, Airtight Plastic Storage Container Set I Gifting Set I Multi-Purpose Box I Serving Set with 4 Section, Pink",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": null,
      "canAddToCart": false,
      "totalReviewCount": 11,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 5,
      "digitalProduct": false,
      "ratingValue": 5,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41Nbhv6fIdL.jpg",
      "asin": "B0CR48X534",
      "productLink": "/dp/B0CR48X534/ref=va_live_carousel",
      "brand": "YouBee",
      "dealBadge": null,
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9299.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-57%",
      "title": "SHIOK DECOR™ Dish Plate Storage Drainboard, Tomorotec Pot Lid Holder Dish Rack Plate Drying Drainer Stand Cabinet Organizer",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9699.00",
      "canAddToCart": false,
      "totalReviewCount": 384,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/51QnjZk+-FL.jpg",
      "asin": "B084631QJC",
      "productLink": "/dp/B084631QJC/ref=va_live_carousel",
      "brand": "SHIOK DECOR",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "57% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9299.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-63%",
      "title": "Epsilon Hanger for Clothe Hanging Over The Door Hook Hanger Heavy Duty Bathroom Towel Organizer Rack with 6 Hooks No Drill No Nail Strong Metal Black",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9799.00",
      "canAddToCart": false,
      "totalReviewCount": 175,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.1,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41rIV2ldxdL.jpg",
      "asin": "B09LS9YT8P",
      "productLink": "/dp/B09LS9YT8P/ref=va_live_carousel",
      "brand": "Epsilon",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "63% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9935.00",
      "hasHalfStar": true,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-69%",
      "title": "PrimeWorld Bistro European Style Crystal Clear 320 ml Red Wine and White Wine Glasses Set of 6 pcs, 100% Lead Free Glass, Unique Modern Design",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b92,999.00",
      "canAddToCart": false,
      "totalReviewCount": 845,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.3,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41qTW09SLeL.jpg",
      "asin": "B0B555Q989",
      "productLink": "/dp/B0B555Q989/ref=va_live_carousel",
      "brand": "PrimeWorld",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "69% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9699.00",
      "hasHalfStar": false,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-63%",
      "title": "Castleite Angels Melamine Plates Set of 6 - Snack Platters for Serving Breakfast or Fancy Buffet at Home or a Café (7 Inches, Marble White)",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b91,899.00",
      "canAddToCart": false,
      "totalReviewCount": 53,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 3.8,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/31yS+Iw1YmL.jpg",
      "asin": "B0B8TD1WPW",
      "productLink": "/dp/B0B8TD1WPW/ref=va_live_carousel",
      "brand": "Castleite",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "63% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  },
  {
      "singularItem": false,
      "promotionType": null,
      "formattedPriceV2": "\u20b9699.00",
      "hasHalfStar": true,
      "primeBenefitSaving": null,
      "formattedSellerDiscountPercentage": "-18%",
      "title": "AGARO Galaxy 6 Pcs Kitchen Knife Set with Wooden Case, 4 Knives, 1 Scissor, 1 Wooden Case, High Carbon Stainless Steel, Non Slip Triple Rivet Strong Handle, Cooking, Cutting, Slicing, Silver",
      "eligibleForPrimeShipping": false,
      "formattedListPrice": "\u20b9849.00",
      "canAddToCart": false,
      "totalReviewCount": 3473,
      "formattedPrimePrice": null,
      "promotions": null,
      "starCount": 4,
      "digitalProduct": false,
      "ratingValue": 4.3,
      "totalPercentageOff": null,
      "outOfStock": false,
      "formattedImageUrl": "https://images-na.ssl-images-amazon.com/images/I/41GIMjbwFUS.jpg",
      "asin": "B083M7M1BS",
      "productLink": "/dp/B083M7M1BS/ref=va_live_carousel",
      "brand": "AGARO",
      "dealBadge": {
          "messageText": "Limited time deal",
          "messageBackgroundColor": "ffffff",
          "messageTimerEndTime": null,
          "labelBackgroundColor": "CC0C39",
          "labelText": "18% off",
          "messageColor": "CC0C39",
          "labelColor": "ffffff"
      },
      "offerListingId": null
  }
];

export default prodObj;